### ISSUE TITLE
Support password setting / 支持设置密码

### ISSUE THREAD

**Issue by xxaier** [CeresDB/ceresdb#1016]
### Describe This Problem

No password will add a lot of complexity to the configuration of firewalls and permissions. 
It is recommended to support passwords

无密码对部署来说会添加很多防火墙和权限的配置复杂度，建议可以支持密码

### Proposal

https://docs.victoriametrics.com/vmauth.html
Password authentication can be embedded, or consider using vauth as an authentication gateway
密码鉴权可以做成嵌入式的，也可以考虑参考vauth做一个鉴权的网关

### Additional Context

Access passwords are a basic function of the database
访问密码对数据库是一个基础功能

**Comment by jiacai2050** [comment]
Hi, we can add a simple user system based on config files, such as this syntax:
```toml
[server.auth]
enable = true
# available values: file/ceresmeta
source = "file"

[server.auth.file]
username = "admin"
token = "secret-token"
```

Does this method solve your problem?

> PS: In a fully cluster deployment, we may store user info in ceresmeta.
