### ISSUE TITLE
Version in Cargo.toml is inconsistent with the release

### ISSUE THREAD

**Issue by archerny** [CeresDB/ceresdb#324]
### Describe this problem

We are going to release a new version 0.4.0, however, I found that the version field in Cargo.toml is still 0.1.0. And besides that , version field in previous releases were inconsistent too.

### Steps to reproduce

Cargo.toml
``` toml
[package]
name = "ceresdb"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"
```
Current output of build.rs is shown below:
```
cargo:rustc-env=VERGEN_BUILD_TIMESTAMP=2022-10-19T16:55:23.452301+00:00
cargo:rustc-env=VERGEN_BUILD_SEMVER=0.1.0
cargo:rustc-env=VERGEN_GIT_BRANCH=main
cargo:rustc-env=VERGEN_GIT_COMMIT_TIMESTAMP=2022-10-19T07:25:54+00:00
cargo:rustc-env=VERGEN_GIT_SEMVER=0.1.0
cargo:rustc-env=VERGEN_GIT_SHA_SHORT=d7c80c1
cargo:rerun-if-changed=/Users/chenwr/workspace/ceresdata/ceresdb/.git/HEAD
cargo:rerun-if-changed=/Users/chenwr/workspace/ceresdata/ceresdb/.git/refs/heads/main
```

### Expected behavior

Version field should be consistent with current release veresion.
